CREATE TABLE IF DOES NOT EXISTS UserName(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name TEXT,
    counter INT
);

CREATE TABLE IF DOES NOT EXISTS Days(
    id INT PRIMARY KEY AUTO_INCREMENT,
    Days_In_A_Week TEXT,
);

CREATE TABLE IF DOES NOT EXISTS Waiters(
    user_id INT REFERENCES UserName(id) ON DELETE CASCADE ON UPDATE CASCADE,
    day_id INT REFERENCES Days(id) ON DELETE CASCADE ON UPDATE CASCADE
);


